from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Date,
    DateTime,
    Numeric,
    ForeignKey,
    Enum,
    Time,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .database import Base


# =========================
# CATEGORIES
# =========================

class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, server_default=func.current_timestamp())

    shops = relationship("Shop", back_populates="category")


# =========================
# SHOPS
# =========================

class Shop(Base):
    __tablename__ = "shops"

    id = Column(Integer, primary_key=True, index=True)
    shop_code = Column(String(20), unique=True, nullable=False)
    name = Column(String(150), nullable=False)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False)
    floor = Column(String(30), nullable=False)
    area_sqft = Column(Numeric(10, 2), nullable=False)
    monthly_rent = Column(Numeric(12, 2), nullable=False)

    status = Column(
        Enum("OCCUPIED", "VACANT", "MAINTENANCE"),
        nullable=False,
        default="VACANT",
    )

    created_at = Column(DateTime, server_default=func.current_timestamp())

    category = relationship("Category", back_populates="shops")
    leases = relationship("Lease", back_populates="shop")

    # Retail sales generated by this shop
    sales = relationship(
        "Sale",
        back_populates="shop"
    )

    # Support / maintenance requests for this shop
    support_requests = relationship(
        "SupportRequest",
        back_populates="shop"
    )


# =========================
# TENANTS
# =========================

class Tenant(Base):
    __tablename__ = "tenants"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(150), nullable=False)
    email = Column(String(150), nullable=False, unique=True)
    phone = Column(String(20), nullable=False)
    company_name = Column(String(150), nullable=True)
    gst_number = Column(String(20), nullable=True, unique=True)
    created_at = Column(DateTime, server_default=func.current_timestamp())

    leases = relationship(
        "Lease",
        back_populates="tenant"
    )

    # Retail sales generated by this tenant
    sales = relationship(
        "Sale",
        back_populates="tenant"
    )

    # Support / maintenance requests created by this tenant
    support_requests = relationship(
        "SupportRequest",
        back_populates="tenant"
    )


# =========================
# LEASES
# =========================

class Lease(Base):
    __tablename__ = "leases"

    id = Column(Integer, primary_key=True, index=True)
    lease_number = Column(String(30), unique=True, nullable=False)

    shop_id = Column(Integer, ForeignKey("shops.id"), nullable=False)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False)

    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)

    monthly_rent = Column(Numeric(12, 2), nullable=False)

    maintenance_charge = Column(
        Numeric(12, 2),
        nullable=True,
        default=0,
    )

    security_deposit = Column(
        Numeric(12, 2),
        nullable=True,
        default=0,
    )

    status = Column(
        Enum(
            "ACTIVE",
            "EXPIRING_SOON",
            "EXPIRED",
            "TERMINATED",
        ),
        nullable=False,
        default="ACTIVE",
    )

    created_at = Column(DateTime, server_default=func.current_timestamp())

    shop = relationship(
        "Shop",
        back_populates="leases"
    )

    tenant = relationship(
        "Tenant",
        back_populates="leases"
    )

    invoices = relationship(
        "Invoice",
        back_populates="lease"
    )


# =========================
# INVOICES
# =========================

class Invoice(Base):
    __tablename__ = "invoices"

    id = Column(Integer, primary_key=True, index=True)
    invoice_number = Column(
        String(30),
        unique=True,
        nullable=False
    )

    lease_id = Column(
        Integer,
        ForeignKey("leases.id"),
        nullable=False
    )

    billing_month = Column(
        Date,
        nullable=False
    )

    rent_amount = Column(
        Numeric(12, 2),
        nullable=False
    )

    maintenance_amount = Column(
        Numeric(12, 2),
        nullable=True,
        default=0
    )

    utility_amount = Column(
        Numeric(12, 2),
        nullable=True,
        default=0
    )

    subtotal = Column(
        Numeric(12, 2),
        nullable=False
    )

    tax_amount = Column(
        Numeric(12, 2),
        nullable=True,
        default=0
    )

    total_amount = Column(
        Numeric(12, 2),
        nullable=False
    )

    due_date = Column(
        Date,
        nullable=False
    )

    status = Column(
        Enum(
            "PENDING",
            "PARTIALLY_PAID",
            "PAID",
            "OVERDUE",
        ),
        nullable=False,
        default="PENDING",
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp()
    )

    lease = relationship(
        "Lease",
        back_populates="invoices"
    )

    payments = relationship(
        "Payment",
        back_populates="invoice"
    )


# =========================
# PAYMENTS
# =========================

class Payment(Base):
    __tablename__ = "payments"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    invoice_id = Column(
        Integer,
        ForeignKey("invoices.id"),
        nullable=False
    )

    amount = Column(
        Numeric(12, 2),
        nullable=False
    )

    payment_date = Column(
        Date,
        nullable=False
    )

    payment_method = Column(
        Enum(
            "CASH",
            "CARD",
            "UPI",
            "BANK_TRANSFER",
        ),
        nullable=False,
    )

    transaction_reference = Column(
        String(100),
        nullable=True
    )

    status = Column(
        Enum(
            "SUCCESS",
            "FAILED",
            "REFUNDED",
        ),
        nullable=False,
        default="SUCCESS",
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp()
    )

    invoice = relationship(
        "Invoice",
        back_populates="payments"
    )


# =========================
# USERS
# =========================

class User(Base):
    __tablename__ = "users"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    name = Column(
        String(100),
        nullable=False
    )

    email = Column(
        String(150),
        unique=True,
        nullable=False
    )

    password_hash = Column(
        String(255),
        nullable=False
    )

    role = Column(
        Enum(
            "ADMIN",
            "MANAGER",
            "TENANT",
        ),
        nullable=False,
        default="TENANT",
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )


# =========================
# RESTAURANTS
# =========================

class Restaurant(Base):
    __tablename__ = "restaurants"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    shop_id = Column(
        Integer,
        ForeignKey("shops.id"),
        unique=True,
        nullable=False,
    )

    cuisine = Column(
        String(100),
        nullable=False
    )

    price_range = Column(
        Enum(
            "BUDGET",
            "MODERATE",
            "PREMIUM",
        ),
        nullable=False,
        default="MODERATE",
    )

    opening_time = Column(
        Time,
        nullable=False,
    )

    closing_time = Column(
        Time,
        nullable=False,
    )

    description = Column(
        Text,
        nullable=True
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )

    shop = relationship("Shop")

    offers = relationship(
        "Offer",
        back_populates="restaurant",
    )

    reviews = relationship(
        "Review",
        back_populates="restaurant",
    )


# =========================
# OFFERS
# =========================

class Offer(Base):
    __tablename__ = "offers"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    restaurant_id = Column(
        Integer,
        ForeignKey("restaurants.id"),
        nullable=False,
    )

    title = Column(
        String(150),
        nullable=False,
    )

    description = Column(
        String(500),
        nullable=True,
    )

    discount_percentage = Column(
        Numeric(5, 2),
        nullable=True,
    )

    valid_from = Column(
        Date,
        nullable=False,
    )

    valid_until = Column(
        Date,
        nullable=False,
    )

    status = Column(
        Enum(
            "ACTIVE",
            "EXPIRED",
            "INACTIVE",
        ),
        nullable=False,
        default="ACTIVE",
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )

    restaurant = relationship(
        "Restaurant",
        back_populates="offers",
    )


# =========================
# REVIEWS
# =========================

class Review(Base):
    __tablename__ = "reviews"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    restaurant_id = Column(
        Integer,
        ForeignKey("restaurants.id"),
        nullable=False,
    )

    customer_name = Column(
        String(100),
        nullable=False,
    )

    rating = Column(
        Integer,
        nullable=False,
    )

    comment = Column(
        String(500),
        nullable=True,
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )

    restaurant = relationship(
        "Restaurant",
        back_populates="reviews",
    )


# =========================
# RETAIL SALES
# =========================
#
# This is DIFFERENT from the existing
# manager payment/collection system.
#
# Retail Sale:
#
# Tenant → Shop → Customer Purchase
#
# Example:
# Aarav → Zara F-101 → Customer buys Jacket
#
# =========================

class Sale(Base):
    __tablename__ = "sales"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    sale_number = Column(
        String(30),
        unique=True,
        nullable=False,
        index=True,
    )

    # -------------------------
    # Shop
    # -------------------------

    shop_id = Column(
        Integer,
        ForeignKey("shops.id"),
        nullable=False,
    )

    # -------------------------
    # Tenant
    # -------------------------

    tenant_id = Column(
        Integer,
        ForeignKey("tenants.id"),
        nullable=False,
    )

    # -------------------------
    # Customer
    # -------------------------

    customer_name = Column(
        String(150),
        nullable=False,
    )

    customer_phone = Column(
        String(20),
        nullable=True,
    )

    # -------------------------
    # Product
    # -------------------------

    product_name = Column(
        String(200),
        nullable=False,
    )

    product_category = Column(
        String(100),
        nullable=True,
    )

    # -------------------------
    # Pricing
    # -------------------------

    quantity = Column(
        Integer,
        nullable=False,
        default=1,
    )

    unit_price = Column(
        Numeric(12, 2),
        nullable=False,
    )

    total_amount = Column(
        Numeric(12, 2),
        nullable=False,
    )

    # -------------------------
    # Payment
    # -------------------------

    payment_method = Column(
        Enum(
            "CASH",
            "CARD",
            "UPI",
            "BANK_TRANSFER",
        ),
        nullable=False,
    )

    transaction_reference = Column(
        String(100),
        nullable=True,
    )

    # -------------------------
    # Dates
    # -------------------------

    sale_date = Column(
        DateTime,
        nullable=False,
        server_default=func.current_timestamp(),
    )

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )

    # -------------------------
    # Relationships
    # -------------------------

    shop = relationship(
        "Shop",
        back_populates="sales",
    )

    tenant = relationship(
        "Tenant",
        back_populates="sales",
    )


# =========================
# SUPPORT / MAINTENANCE
# =========================
#
# Tenant creates a request
# for their leased shop.
#
# Tenant → Active Lease → Shop
#                    ↓
#             Support Request
#
# Manager can view and update
# all support requests.
#
# =========================

class SupportRequest(Base):
    __tablename__ = "support_requests"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    request_number = Column(
        String(30),
        unique=True,
        nullable=False,
        index=True,
    )

    # -------------------------
    # Shop
    # -------------------------

    shop_id = Column(
        Integer,
        ForeignKey("shops.id"),
        nullable=False,
    )

    # -------------------------
    # Tenant
    # -------------------------

    tenant_id = Column(
        Integer,
        ForeignKey("tenants.id"),
        nullable=False,
    )

    # -------------------------
    # Request Type
    # -------------------------

    request_type = Column(
        Enum(
            "MAINTENANCE",
            "ELECTRICAL",
            "PLUMBING",
            "CLEANING",
            "SECURITY",
            "HVAC",
            "IT",
            "OTHER",
        ),
        nullable=False,
        default="MAINTENANCE",
    )

    # -------------------------
    # Request Details
    # -------------------------

    subject = Column(
        String(200),
        nullable=False,
    )

    description = Column(
        Text,
        nullable=False,
    )

    # -------------------------
    # Priority
    # -------------------------

    priority = Column(
        Enum(
            "LOW",
            "MEDIUM",
            "HIGH",
            "URGENT",
        ),
        nullable=False,
        default="MEDIUM",
    )

    # -------------------------
    # Status
    # -------------------------

    status = Column(
        Enum(
            "OPEN",
            "IN_PROGRESS",
            "RESOLVED",
            "CLOSED",
        ),
        nullable=False,
        default="OPEN",
    )

    # -------------------------
    # Manager Response
    # -------------------------

    manager_response = Column(
        Text,
        nullable=True,
    )

    # -------------------------
    # Dates
    # -------------------------

    created_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
    )

    updated_at = Column(
        DateTime,
        server_default=func.current_timestamp(),
        onupdate=func.current_timestamp(),
    )

    # -------------------------
    # Relationships
    # -------------------------

    shop = relationship(
        "Shop",
        back_populates="support_requests",
    )

    tenant = relationship(
        "Tenant",
        back_populates="support_requests",
    )